apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: devops-rabbitmq-cluster
spec:
  image: rabbitmq:3-management
  override:
    service:
      spec:
        ports:
          - name: http
            protocol: TCP
            port: 15672
            targetPort: 15672
          - name: amqp
            protocol: TCP
            port: 5672
            targetPort: 5672
  replicas: 3
  resources:
    requests:
      cpu: "0.5"
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
